### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by jorgyz** [huangzehao/caffe-vdsr#1]
Hi,

Thanks for sharing your code.  What is the best way to use the trained model to get the upsampled version of a new image?

Thanks!

**Comment by huangzehao** [comment]
Please check the test code I just uploaded. It's a simple test code and you can modify it to upsample your images.  
In my opinion, MatConvNet is a good tool in matlab to test convolutional neural network. Actually, you can use the trained model by many tools in different languagues, like opencv, caffe, MatConvNet, matlab and python. It depends on yourselves.

Hope this helps!

**Comment by jorgyz** [comment]
Many thanks, @huangzehao!
