### ISSUE TITLE
关于参数提取问题

### ISSUE THREAD

**Issue by zhangfudiyi** [huangzehao/caffe-vdsr#10]
你好！我看了你的代码不知道怎么去保存训练好的模型参数，希望你能上传一份你的代码给我们吗？不胜感激！谢谢了！

**Comment by huangzehao** [comment]
check the code 'caffemodel2mat.m' in Train.

**Comment by zhangfudiyi** [comment]
@huangzehao  谢谢！我好久以前就fork了你的代码，但是没注意你有更新了代码！ 谢谢！
