### ISSUE TITLE
Need help for DRCN model

### ISSUE THREAD

**Issue by BaiYu0120** [huangzehao/caffe-vdsr#13]
Hi, my inplement of DRCN model did not show better performance than VDSR, can you help me to check the net.prototxt? 
baiyupc@163.com,this is my email address , can you send me your email address?

**Comment by huangzehao** [comment]
Hi, this is my emial address, huangzehao@outlook.com.

**Comment by BaiYu0120** [comment]
Email has been sent.

**Comment by huangzehao** [comment]
Hi, maybe there are some problems in the loss setting. Check this http://caffe.berkeleyvision.org/tutorial/loss.html and set specific loss_weight in each loss layer.
layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "pred"
  bottom: "label"
  top: "loss"
  loss_weight: 1
}
