### ISSUE TITLE
Can't reach the performance of your implementation

### ISSUE THREAD

**Issue by hacql2004** [huangzehao/caffe-vdsr#14]
Hi, first of all thanks for sharing your code of vdsr.
I followed your code rencently. My training data is from 291 images (with data augumentation and factor 2) . I used your 'generate_train.m' to generate 148288 41*41 patches in all.  The net and deploy prototxt files are the same as yours.  The training procedure is about 73 epoches.
However, my implementation can't reach your performance on Set5 (using model VDSR_170000.mat). Here is my result.
VDSR_Official 37.55 
YOUR_VDSR_170000 37.42
MY_VDSR_170000 37.14
It can be found that there is a obvious difference between my result and yours.
Can you help me to figure out what's the problem of my impementation? Thanks a lot.

**Comment by huangzehao** [comment]
More training samples are better
VDSR_Official: 9000 iterations \* 64 =  576 000, about 600000 samples are used.
VDSR_My: 5000 iterations \* 64 = 320000, about 300000 samples are used.

**Comment by hacql2004** [comment]
Okay， I will try this later, thank u. 
By the way , what do you think of adding layers & enlarging the input image size in vdsr,
is this a good way to improve the performance of vdsr?

**Comment by huangzehao** [comment]
Yes. But it will be slower.
