### ISSUE TITLE
I'm wondering is there some other things need to do in the traing progresss?

### ISSUE THREAD

**Issue by wxywb** [huangzehao/caffe-vdsr#15]
At first thanks for your work. I just run the code with caffe and get a iter_200000 model, and test it by your matlab code.But it looks doesn't have the performance compared to your 170000  iterations counterpart.Is there some training tricks I need to do during training progress?(like decrease the learning rate or other things). 
ps:the test loss decreases quickly and stucked at about average 0.185 after 30000 iterations.

**Comment by huangzehao** [comment]
Hi, 170000 model is trained by the sovler.prototxt in this repository. There aren't training tricks in my experiment. 
In my opinion, more training sample will help your training. About 300000 training samples are used in my training.

**Comment by wxywb** [comment]
Thanks for reply, I found that in the original patch-generation code, there are 20288 patches cropped from 91 images dataset, and you use data augmentation to get 300000 patches from these 91 images,right?

**Comment by huangzehao** [comment]
Yes

在 2016年10月10日，18:57，Xianyu Wang <notifications@github.com<mailto:notifications@github.com>> 写道：

Thanks for reply, I found that in the original patch-generation code, there are 20288 patches cropped from 91 images dataset, and you use data augmentation to get 300000 patches from these 91 images,right?

―
