### ISSUE TITLE
你好！我想请教一下。

### ISSUE THREAD

**Issue by zhangfudiyi** [huangzehao/caffe-vdsr#16]
我用了60多万张图片，每个scale 2/3/4 按等分的。每个hdf5文件中都包含3个scale的训练样本，为什么我无论怎么训练都无法达到作者提供的模型呢！而且测试set5的图片一般都会相差0.3到0.4左右，大神能不能帮我分析一下什么原因么？

**Comment by huangzehao** [comment]
Hi, I didn't reproduce the multi scale result too. My results are worse about 0.1~0.2 dB. Actually my training solver is not the best setting, this is one of the reasons. And maybe there are  some trick in the training of multi scale. You can email the author for help.

**Comment by zhangfudiyi** [comment]
clip_gradients 有没有测试其他的下降值，比如0.01 0.2 0.5 。我怀疑是不是这个问题。我的电脑训练太慢了 ，不然我想测试一下。我也邮件问了作者，发过去完全没反应，都不理我。
