### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by lava1368** [huangzehao/caffe-vdsr#19]
hi. Firstly, thanks for your source code. i wonder how can you do data augmentation to get 300000 sample data. could you explain this a little bit? did you use real time data augmentation during training or you do preprocessing likes image affinetransform. Cause i am struggle with real time data augmentation in Caffe

**Comment by huangzehao** [comment]
I trained my "VDSR_170000" model by about 300000 training samples (1638 images augumented from 91 images). 
You can easily get 1638 images from 91 images by simple transforms, like rotation, crop, flip and translation。

**Comment by lava1368** [comment]
thanks for your quick reply, i understand now. have you ever try real time data augmentation in Caffe? do you think it is better than preprocessing the traing data? similar with this https://github.com/kevinlin311tw/caffe-augmentation

**Comment by huangzehao** [comment]
I didn't try real time data augmentation in caffe. You can have a try. In my opinion, it wil be more effective.

**Comment by lava1368** [comment]
ok i will try to do it. one again thanks
