### ISSUE TITLE
About the image normalize

### ISSUE THREAD

**Issue by jackie840129** [huangzehao/caffe-vdsr#20]
Hi ,can I ask a question that did you normalize or /255 to your image when you train your model?
I didn't see that in any script under the Train directory, but I found that in the Test/Demo_SR_Conv.m. 
Thanks.!

**Comment by huangzehao** [comment]
There is a code 'im2double()' in generate_train.m, it normalize original image to 0~1 by divide 255.

**Comment by jackie840129** [comment]
Oh! I missed it!  Thank you very much!

**Comment by jackie840129** [comment]
Sorry, I found that someone ask a question about augmentation, and I have some questions.
Can I ask you that how you preprocess your image?
I can see from your project page that there are 91/  291/ , two sets of image.
and I know you split your image to many 41x41 pieces.
But I cannot find the code how you augment your image. Thanks.

**Comment by huangzehao** [comment]
I didn't provide the code of augmentation. You should do it by yourself.  Including rotation, flip and translation.
