### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by saeed-anwar** [huangzehao/caffe-vdsr#23]
Hi,

I would like to know how you increased the images from 91 to 1638.

Any info will be highly appreciated.

Regards,

**Comment by huangzehao** [comment]
Hi, check this issue. #19
Thanks.

**Comment by saeed-anwar** [comment]
Thanks,

I seems that you have applied around 17 to 18 different transformation, can you share the training file, where these transformation occurs.

Cheers,

**Comment by huangzehao** [comment]
Sorry, I can't fine the code of data augmentation right now since I wrote this code long ago.

You can write it by yourself. It's very simple in matlab. 
Like this:
```
image_rotate = imrotate(image,rotate_angle);
image_flip = flip(image,2);
image_translate = immove(image,translate_x,translate_y);
image_zoom = imresize(image,zoom_scale,'bicubic');
```

**Comment by saeed-anwar** [comment]
I am doing it in matlab, but I am not getting the same results as yours. Thats why I asked for the specific data augmentation types.

cheers.

**Comment by huangzehao** [comment]
How many training samples you used during training?
And what's your solver setting?

**Comment by saeed-anwar** [comment]
The solver setting is same as yours, and the number of samples are around 600k from (582 data augmented, flipped only from 291 images)

**Comment by huangzehao** [comment]
Hi, you should modify the solve setting since your number of training samples is different from mine.
Check the readme I just updated, and do training again.
I hope this helps.
Thanks!
