### ISSUE TITLE
How to use your VDSR_170000.mat model in caffe

### ISSUE THREAD

**Issue by RyanCV** [huangzehao/caffe-vdsr#28]
Hi, I am wondering how to change the VDSR_170000.mat or VDSR_Official.mat model in order to run test in caffe?? Thanks.

**Comment by huangzehao** [comment]
Hi, read http://caffe.berkeleyvision.org/tutorial/interfaces.html and https://github.com/huangzehao/caffe-vdsr/blob/master/Train/caffemodel2mat.m, you can chane the mat model to caffemodel.

**Comment by shateng** [comment]
hi, 我用10W张41*41的图像对进行训练，但不管怎么调学习率貌似都无法收敛的很好，平均cost在150左右，你当时训练结束时的cost大概是多少呢?能留个联系方式吗

**Comment by shateng** [comment]
加上addto layer后cost是停留在30左右

**Comment by huangzehao** [comment]
@shateng I have updated the full implementation of VDSR. Check it and try again!
