### ISSUE TITLE
random white pixels in superres image

### ISSUE THREAD

**Issue by jorgyz** [huangzehao/caffe-vdsr#3]
Hi,

I have successfully trained a model and the output images look good, with one exception.  For some reason I get a lot of stray white pixels in dark areas of the image. I have attached an example.  Some images only have a few of these stray pixels, while others (like this one) have many.  Any idea what might be causing this?

Thanks!
![badzebra](https://cloud.githubusercontent.com/assets/15148653/16088127/46f81e4c-32eb-11e6-82be-9383266269ae.png)

**Comment by huangzehao** [comment]
Hi, how did you get your HR image? I met this problem when I use imresize function from python version opencv. You can check the value in these pixels, are they NAN?

**Comment by jorgyz** [comment]
Thanks for your response.  I fixed the issue...it was due to negative values in the output from the network. I replaced them with zero before converting back to RGB and it fixed the problem.
Thanks!

**Comment by Pepslee** [comment]
jorgyz, I need your help !
Did you solve the issue with Caffe SegNet ?  
[https://github.com/alexgkendall/caffe-segnet/issues/24])
I have similar problem, can you help me ?
