### ISSUE TITLE
Caffemodels corresponding to VDSR_official.mat and VDSR_ADAM.mat

### ISSUE THREAD

**Issue by burhanmudassar** [huangzehao/caffe-vdsr#30]
Hi,

Is it possible for you to provide the caffemodel snapshot corresponding to the above models?

**Comment by huangzehao** [comment]
Hi, I can provide VDSR_ADAM's caffemodel. The VDSR_official is convert from original paper, and there is not corresponding caffemodel.

**Comment by burhanmudassar** [comment]
Great. Can you email me at burhanahmadmudassar@gmail.com or any other way you prefer to share it

**Comment by huangzehao** [comment]
Hi, it's been uploaded in https://github.com/huangzehao/caffe-vdsr/blob/master/Train/VDSR_Adam.caffemodel.
