### ISSUE TITLE
about the data sample

### ISSUE THREAD

**Issue by Usernamezhx** [huangzehao/caffe-vdsr#32]
hi zehao
      first of all thank you for sharing the code. I have the train sample for 1920x1080 . the num is 5000. i did not do the data_aug. I think the data is enough. but when i run the code generate_train.m .The computer will crash. How should i do. hope your reply.

**Comment by huangzehao** [comment]
Hi, I think it's caused by the memory issue. The memory of your computer is so small to hold on the training samples. Split your train sample into multi groups and generate multi training files may help.

**Comment by Usernamezhx** [comment]
hi zehao
    thanks for your reply. you means that i split the sample and then to run generate_train.m 	
separately. then i will get several hdf5. after that i write down their path to the  source: "examples/VDSR/train.txt" .is that right? i will try first.many thanks.

**Comment by huangzehao** [comment]
Yes.
in train.txt, you can write path like this:
./train_1.h5
./train_2.h5
./train_3.h5
