### ISSUE TITLE
Error in VDSR_Matconvnet (line 15)

### ISSUE THREAD

**Issue by xujinchang** [huangzehao/caffe-vdsr#35]
hi， when i want to test the vdsr model by using matlab , i have met the following errors:
iter:1
Attempt to execute SCRIPT vl_nnconv as a function:
/local/home/share/xujinchang/project/learn_pytorch/caffe-vdsr-master/Test/matconvnet/matlab/vl_nnconv.m

Error in VDSR_Matconvnet (line 15)
    convfea = vl_nnconv(im_y,weight{1},bias{1},'Pad',1);

Error in Demo_SR_Conv (line 43)
im_h_y = VDSR_Matconvnet(im_l_y, model,up_scale,use_cascade);

Thanks!

**Comment by huangzehao** [comment]
Hi, have you compiled the matconvnet library? Following http://www.vlfeat.org/matconvnet/install/ and have a try.

**Comment by xujinchang** [comment]
@huangzehao Thanks a lot, I have compiled the matconvnet library followed the http://www.vlfeat.org/matconvnet/install/ , but now the error just likes this:
>> Demo_SR_Conv
Undefined function or variable 'VDSR_Matconvnet'.
Error in Demo_SR_Conv (line 42)
im_h_y = VDSR_Matconvnet(im_l_y, model,up_scale,use_cascade);
i can't find where you have defined the function of VDSR_Matconvnet, 
thanks for your help!

**Comment by huangzehao** [comment]
Did you clone the full repo?
VDSR_Matconvnet is defined in utils.
https://github.com/huangzehao/caffe-vdsr/blob/master/Test/utils/VDSR_Matconvnet.m

**Comment by xujinchang** [comment]
@huangzehao thanks for your help with patience, i have run the test successfully.The results seem like these:
iter:1
Elapsed time is 1.711943 seconds.
sr_psnr: 29.954547 dB
bi_psnr: 24.038857 dB
