### ISSUE TITLE
Questions about parameters

### ISSUE THREAD

**Issue by Hellcat1005** [huangzehao/caffe-vdsr#38]
Hello, author. Thanks for your work. 

I have some questions about the parameters. The input size is 41x41 when you generate training set. After training, you get a model based on the size 41x41. Can this model work well when you reconstruct an image whose size is quite different, like 2000x2000? I trained a model using your code. Everything is same except for the down sampling method(I did not use imreszie).  I found when the size of the image is small, like 100x100, I got better PSNR and SSIM than bicubic interpolation. If the size of the image increases, bicubic interpolation will be bettter than VDSR. Do you think it is because of the input size? The other question is that, in the file VDSR_net_deploy.prototxt, the last two input_dim are set to 256, I don't understand where this value come from. 

I'm looking forward to your reply. Thanks.

**Comment by huangzehao** [comment]
Hi, I didn't test verg large image like 2000x2000. You can try my trained model to check the performance of large image. There maybe something wrong in your training.
The last two input_dim should be changed to fit your input image. 256 is just a example.

**Comment by Hellcat1005** [comment]
Thanks. I didn't use function modcrop to process the image. I add modcrop now, then VDSR is better than bicubic interpolation for large image.
