### ISSUE TITLE
About learning rate

### ISSUE THREAD

**Issue by Hellcat1005** [huangzehao/caffe-vdsr#41]
Hi, I have a question about the learning rate. I notice that you set the learning rate to 0.0001 for weight and 0.00001 for bias. The training result with these two values is pretty good. I am curious that how you find these two values? Just keep trying or you have some methods to set learning rates? Could you talk about what you did when you tried to find appropriate learning rates? Thanks.

**Comment by huangzehao** [comment]
Hi, I follow the setting of SRCNN to set the lr_mult of bias as 1/10 of weight. And 0.0001 for adam is a very popular choice.

**Comment by Hellcat1005** [comment]
Thanks a lot!
