### ISSUE TITLE
File for training data is offline – alternative location?

### ISSUE THREAD

**Issue by subzerofun** [huangzehao/caffe-vdsr#42]
As the title states – the link unfortunately doesn't work anymore:
http://cv.snu.ac.kr/research/VDSR/train_data.zip

Do you know of an alternative server or could you upload the file somewhere?

Thank you!

**Comment by LucyLu-LX** [comment]
Same Problem's  Here.

**Comment by huangzehao** [comment]
Hi, download from 
[google driver](https://drive.google.com/file/d/1wKm-cRzbBO5aVvz2s9uJfiQwprH27x07/view?usp=sharing) or 
[baidu yun](https://pan.baidu.com/s/1mhDcbu4) password: ysqp
