### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by sdlpkxd** [huangzehao/caffe-vdsr#43]
Hi, I have questions about the training data. I use you generate_train.m to get the training data file and the training data set is 291. But I just get 54144 samples. In Issue Multi-Scale Implementation you say you get about 748000 samples, did you do  data pretreatment (for example, rotating the picture with
the degree of 90, 180 and 270) to the training data set ?

Thanks

**Comment by huangzehao** [comment]
Hi, refer
https://github.com/huangzehao/caffe-vdsr/blob/master/Train/data_aug.m

**Comment by sdlpkxd** [comment]
thank you very much.
