### ISSUE TITLE
Thanks and some questions

### ISSUE THREAD

**Issue by Amy-A** [huangzehao/caffe-vdsr#46]
Hi Huang,thanks your sharing! But I have some question.
1.The relation of Training image data and the image I want to rebuild.I mean if i want to rebuild some low resolution images of human face. Do you think my Training data should be all the human face images? Or I should make my Training data the more types, the better?
2. The Size of the cutting image in the file "generate_train". I mean you choose the 41*41 size to cut the training data cause most paper choose the 91 or 291 images. And the training data all about 300*300 size. If my training data all about 1000*1000, should I make my cutting size larger? If I do it, larger cutting size would learn more or less features?
3.About the Multi-scale. In the paper of VDSR the writer said the"Scale augmentation during training is a key technique to equip a network with super-resolution machines of multiple scales." I could not understand that because in FSRCNN, they also used the aug. I think VDSR make the multi scale because of the files "generate_train" and "generate_test". These two files have a "for scale = 2:4". So I want to ask that which is the most important reason to achieve the multi scale rebuild?
4.The most important reason that The VDSR is better the the SRCNN. I did a lot of trying. But I still don't know the key skill of VDSR. What do you think the most important change of VDSR to make a better PSNR to the SRCNN? Maybe the reason is "sum" in the end of the net make it only learn the difference between low and high resolution images? Or the deeper net 20 layers? (I tried 50 layers but a little little better rebuild effect).
So many questions to ask you. A little ashame ^-^

**Comment by huangzehao** [comment]
Hi, I am not very familiar with face super-resolution.
(1) I suggest you to read some face super-resolution paper and follow their setting to train. 
(2) The multi scale in VDSR is they mix scale 2, 3 and 4 in training. So they can inference difference scale in only one model.
(3) The most importance reason of VDSR are deep network and residual. I suggest you follow the network structure of https://arxiv.org/abs/1609.04802 to train more deeper network.
