### ISSUE TITLE
End-2-end learning or residual learning

### ISSUE THREAD

**Issue by Anvoy** [huangzehao/caffe-vdsr#5]
HI, Thank you for sharing this code for vdsr. I have a question about your implementation. It seems like authors from the paper achieved their performance by learning the residual (HR-interpolated) image. However, in your implementation, it looks like you are only utilizing the ground-truth images during training and you achieve similar results. Have you try to use the residual image at all?

**Comment by huangzehao** [comment]
Hi, my implementation is the same as the original paper. Both learning the residual of HR and LR image. You can check the network in my implementation. Thank you!

**Comment by Anvoy** [comment]
Thank you for your reply. I see where you utilize the residual now. you add a sum layer in the end which is implicitly learning the residual image.

**Comment by Anvoy** [comment]
Hi, sorry to bother you again. I am having some difficulties to achieve the same performance as you did in model_170000. If you don't mind, is there anyway that I can talk with you privately for the matter?

**Comment by huangzehao** [comment]
Hi, my email address huangzehao@outlook.com. You can send me an email to formulate your problem.
