### ISSUE TITLE
After finishing train

### ISSUE THREAD

**Issue by EEENS** [huangzehao/caffe-vdsr#6]
Thanks for sharing your code.

I finished training using caffe but after that i don't know how to test my data. 
In SRCNN, they has matlab code for extracting parameter of caffemodel. Am i made my own code like that? How can you extract parameter from your caffemodel?

**Comment by huangzehao** [comment]
Hi, yes you should write your own code like "saveFilters.m" in SRCNN. 
get weight and bias of layer "conv1" by "net.layers('conv1').params(1).get_data()" and "net.layers('conv1').params(2).get_data()". Then you can save them by your own format. It depends on how you use them in test.

You can read this tutorial and you will understand the codes in "saveFilters.m" in SRCNN.
http://caffe.berkeleyvision.org/tutorial/interfaces.html
