### ISSUE TITLE
question about training time

### ISSUE THREAD

**Issue by BaiYu0120** [huangzehao/caffe-vdsr#8]
hi huang,
I am going to training the x4 models using your vdsr training code and 91 images database, how long time will I take?
It has been running for about 16 hours.

**Comment by huangzehao** [comment]
Hi, it depends on your gpus. You can firstly check the performance of your snapshots and decide when to stop. In my experiment, model trained about 30 epoch can get a good result.

**Comment by BaiYu0120** [comment]
I want to use your test code, can you show me the savefilter code?

**Comment by BaiYu0120** [comment]
Thanks.
I create a savefilter.m just like SRCNN train,  but your test code can not use the .mat doc. Can you show me your save code?

**Comment by zhangfudiyi** [comment]
@huangzehao 你好，请问一下1个epoch是迭代多少次？

**Comment by huangzehao** [comment]
@zhangfudiyi It depends on the number of  training samples and batch size. 
Iters_num of one epoch = training_num / batch_size

**Comment by zhangfudiyi** [comment]
@huangzehao thank you！

**Comment by BaiYu0120** [comment]
Can I use the fast r-cnn to implement the DRCN(recurrent conv layers) Super resolution?
