### ISSUE TITLE
does the scale still matter when generate training and test h5 data?

### ISSUE THREAD

**Issue by pliu007** [huangzehao/caffe-vdsr#9]
According the VDSR paper,  the trained model should fit different scale factor, right ?
If it means the training and test h5 data generating is not affected by the scale factor in the generate_traim.m and generate_test.m ?

**Comment by huangzehao** [comment]
If you want to fit different scale factor in one model, you should generate different scale train samples in one hdf5 data, following original VDSR paper.
Oh, I know where is the problem...
I will fix it.

**Comment by huangzehao** [comment]
If you want to fit different scale factor in one model, you should generate different scale train samples in one hdf5 data, following original VDSR paper.
In my implementation, I only use factor 2 train samples to train the model. So when testing, "VDSR_Official.mat" can generate factor 3 or 4 results directly while "VDSR_170000.mat" need cascade.
